### ISSUE TITLE
Update db reset instructions for local development

### ISSUE THREAD

**Issue by wgwz** [regen-network/regen-server#314]
> I believe we might actually want to update the README accordingly now that we have auth_user role, I guess when resetting the db we should not only drop app_user as currently written but also auth_user, if you only dropped app_user as stated then I guess that might just be the reason for this behavior:
> - when dropping app_user I guess it also removes the fact that auth_user is a member of app_user
> - when running the migrations from a blank db, app_user is created again (v1_0)
> - but since auth_user is still there, v2_10 is skipped, hence GRANT app_user TO auth_user; is not run

https://github.com/regen-network/registry-server/blob/master/README.md#dropping-local-database

/cc @blushi @flagrede

**Comment by blushi** [comment]
This does not apply anymore since we've migrated to graphile-migrate
