### ISSUE TITLE
Add instructions for how to manually add a profile

### ISSUE THREAD

**Issue by wgwz** [regen-network/regen-server#364]
We want to document the process of how to edit a profile manually.
Most commonly this happens when we have a multisig account that cannot use the login system.
Several weeks ago we discussed that we can just add this as a markdown doc here in the regen-server docs:
https://github.com/regen-network/regen-server/tree/dev/docs
This guide will show how to create an account in the database as well as how to make updates to the relevant parts of the corresponding profile in the database.
Typically when I have done this I also need to manually upload profile and background images to S3.
This will document that as well.

**Comment by ryanchristo** [comment]
@wgwz I think this is something we want to tackle sooner than later. Can you update the description?

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-server/364?planning-poker) with Zenhub @blushi @ryanchristo @wgwz
