### ISSUE TITLE
Add approved boolean to project table

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-server#369]
A project should be created with `approved` set to `false` by default. This field will be manually updated.

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-server/369?planning-poker) with Zenhub @blushi @wgwz @ryanchristo

**Comment by wgwz** [comment]
For projects that we already have in the production database, should we set this field to true?
Presumably those are all trusted.
Just wondering if that needs to be part of the migration script.

**Comment by blushi** [comment]
> For projects that we already have in the production database, should we set this field to true? Presumably those are all trusted. Just wondering if that needs to be part of the migration script.

Yeah I think so.

Another thing I thought about is that ideally, we would want to restrict updates on this particular field so that even the admin of the project wouldn't be able to edit it, just the root db user. This might be doable by combining row level security with column grants.

**Comment by wgwz** [comment]
@blushi i gave the update restrictions a try, i think i've got it working but needs some review:
https://github.com/regen-network/regen-server/pull/371
