### ISSUE TITLE
CORS not enabled for production deploy preview

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-server#378]
## Summary

When following the release steps for regen-web, there is a step to check the preview before publishing. This preview link is not supported by our current CORS configuration. We may want to consider adding support for it:

CORS configuration:

https://github.com/regen-network/regen-server/blob/9ac1ff70506558844d826aca2849ec8e6e0230a6/server/Server.ts#L57-L58

Example of preview link:

https://6509caf51822320008c51f72--regen-marketplace.netlify.app/

**Comment by blushi** [comment]
Sorry, only seeing this now, this seems to work on https://dev--regen-marketplace.netlify.app/ for instance so I guess we can close this. This will work too for production previews once we merge `dev` into `master` which should happen shortly.
