### ISSUE TITLE
Implement magic link authentication using passport

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-server#379]
For authentication, we've decided to build a custom solution on top of passport.

The first web2 authentication option we would like to support is magic link authentication:
- https://www.passportjs.org/packages/passport-magic-login/ 

In order to implement this, we will need to add `email` to `party`, which should be unique and nullable.

**Comment by blushi** [comment]
@erikalogie do we have a design for the email with the magic link sent to users?
