### ISSUE TITLE
Clean up database model for web2 authentication

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-server#399]
As discussed in #375, we should proceed to the following:
1. removal of the `account` table as it stands today (this might be addressed by #391)
2. renaming of the `party` table to the `account` table
3. removal of the `wallet` table
4. add `addr` ~~and `email`~~(already done) column to the new `account` table

But 3. and 4. are still being discussed: https://github.com/regen-network/regen-server/issues/375#issuecomment-1737285426

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-server/399?planning-poker) with Zenhub @wgwz

**Comment by blushi** [comment]
@wgwz After thinking about this more, I think we could remove the `wallet` table and handle the edge case mentioned in https://github.com/regen-network/regen-server/issues/375#issuecomment-1737285426 nicely by simply making sure in the project update policy that if the project has some on chain id but the party trying to update it, even if it's the admin_party_id, doesn't have any wallet address, then we don't authorize any updates on it.

**Comment by wgwz** [comment]
@blushi i think that could work. here's a sketch of what the RLS policy could look like ( i think it's at least close...)

```sql
select
  id
from
  project
where
  exists (
    select
      1
    from
      project
      join party on project.admin_party_id = party.id
    where
      project.on_chain_id is not null
      and party.addr is not null
      and party.id = get_current_party()
  );
```

This policy means "allow updates to project rows where on chain id and party addr are not null".

I think we would need an additional RLS condition for the updates that says:
"allow an project admin to update their offchain projects"

Both of these policies would need to be "permissive" I guess.
WDYT? Am I understanding correctly?

**Comment by blushi** [comment]
> @blushi i think that could work. here's a sketch of what the RLS policy could look like ( i think it's at least close... [ref](https://stackoverflow.com/a/71048473))
> 
> ```sql
> select
>   id
> from
>   project
> where
>   exists (
>     select
>       1
>     from
>       project
>       join party on project.admin_party_id = party.id
>     where
>       project.on_chain_id is not null
>       and party.addr is not null
>       and party.id = get_current_party()
>   );
> ```
> 
> This policy means "allow updates to project rows where on chain id and party addr are not null".
> 
> I think we would need an additional RLS condition for the updates that says: "allow an project admin to update their offchain projects"
> 
> Both of these policies would need to be "permissive" I guess. WDYT? Am I understanding correctly?

@wgwz I believe that could work but maybe this could be achieved with a single policy and OR's?

**Comment by wgwz** [comment]
@blushi and i spoke about this in our 1-1 today, and after describing how we could do this in two policies, we agreed it would good to try that approach.
this has at least two nice benefits:
1. each policy can be given an accurate name
2. each policy can be a more focused purpose/query that could be easier to understand

by default, policies in postgresql are "permissive".
this means that multiple policies for the same table/command, are applied in an "or" fashion.
if one of them evaluate to true for any rows, then those rows are targeted.

**Comment by wgwz** [comment]
As part of this task, we need to make sure that these currently disabled tests (which were disabled [in this PR](https://github.com/regen-network/regen-server/pull/398)):
```
./server/__tests__/db/project.update.policy.DISABLED.ts
./server/__tests__/db/project.delete.policy.DISABLED.ts
./server/__tests__/e2e/files.projects.DISABLED.ts
```
Are 1. re-enabled (`s/DISABLED/test`):
```
./server/__tests__/db/project.update.policy.test.ts
./server/__tests__/db/project.delete.policy.test.ts
./server/__tests__/e2e/files.projects.test.ts
```
And 2. that the tests are passing/properly adjusted.
