### ISSUE TITLE
Implement OTPW authentication using passport

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-server#401]
The first web2 authentication option should be based on a one-time password sent via email, similar to the UX provided by https://logto.io/products/passwordless

We need to implement a new passport strategy for this. It doesn't seem like there's any existing open source passport strategy for this. There is https://www.passportjs.org/packages/passport-totp/  but that is meant for 2FA usage, meaning the code is generated by external applications.
If we need to implement a custom strategy, we already have our `keplrStrategy` that could serve as an example.
Some other ressources that could be helpful:
- https://github.com/nickbalestra/zero (a bit outdated)
- https://github.com/florianheinemann/passwordless/

We'll need 2 endpoints that should be added to our existing [/marketplace/v1/auth route](https://github.com/regen-network/regen-server/blob/5cf07ee3b81d218fc05318dce17dc39a838ea291/server/routes/auth.ts):
1. one for sending the email with the OTP
The email sent to the user with the code should look like this:
https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=1514-75392&mode=design&t=GUYNDxgbImiKnEZ4-0
We already have [MJML](https://mjml.io/) setup for building such emails and a very similar one was already built: https://github.com/regen-network/regen-server/blob/5cf07ee3b81d218fc05318dce17dc39a838ea291/server/worker/templates/login_with_magic_link.mjml
This is how we can send emails: https://github.com/regen-network/regen-server/pull/389/files#diff-827bcdf6d2361844ec855ffe61e6474e2ffaed4721a9c56f053c568b05239880R19-R32
2. another endpoint for verifying the code and logging in the user

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-server/401?planning-poker) with Zenhub @blushi @wgwz @ryanchristo @aaronc

**Comment by wgwz** [comment]
A package that might be helpful is this:
- https://www.npmjs.com/package/otplib
- https://www.npmjs.com/package/hotp

[TOTP](https://datatracker.ietf.org/doc/html/rfc6238) uses [HOTP](https://datatracker.ietf.org/doc/html/rfc4226), and HOTP is "an algorithm to generate one-time password values, based on Hashed Message Authentication Code".

Could be good to follow that standard for generating the values.

**Comment by blushi** [comment]
> A package that might be helpful is this:
> 
> * https://www.npmjs.com/package/otplib
> * https://www.npmjs.com/package/hotp
> 
> [TOTP](https://datatracker.ietf.org/doc/html/rfc6238) uses [HOTP](https://datatracker.ietf.org/doc/html/rfc4226), and HOTP is "an algorithm to generate one-time password values, based on Hashed Message Authentication Code".
> 
> Could be good to follow that standard for generating the values.

It seems like TOTP/HOTP are primarily used for MFA. A different secret is associated to each user, which is then used to generate the code/token along with a counter or current time. These algorithms are particular useful for MFA where the code generation and verification are handled by different devices, phone and server respectively. 
So I'm not sure if this is the most suitable for our use case where the user might not exist yet?
I was looking at logto implementation, and they just use a random 6-digit code based on https://github.com/ai/nanoid `customAlphabet`: https://github1s.com/logto-io/logto/blob/1fcb28b31bb2d24aaedcf4fc81a09f478e84a153/packages/core/src/libraries/passcode.ts#L18-L19
In any case, we'll need to temporarily store those secrets or codes somewhere.

**Comment by wgwz** [comment]
Maybe this for generating 6 digits?
https://stackoverflow.com/a/50099582/4028706
