### ISSUE TITLE
Support private columns for the account table

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-server#407]
As part of the web2 auth support (email through passcode and google initially), we added an `email` and `google` columns to the `account` table for storing those info.
But currently any `app_user` is granted SELECT access on all columns on the account table while these columns should remain private and only be available for the authenticated accounts.

We have 2 options to implement this:
- either create a separate private.account table with those `email` and `google`  columns only and return those info as part of the GET /accounts endpoint in addition to the active and authenticated accounts ids ;
- or only GRANT SELECT to `app_user` on the public account columns (all except `email` and `google`) and create a security definer function that would return an account by id with all columns available for any authenticated accounts. This would give us a graphql query through postgraphile, allowing us to keep using the same generated types on the front-end.

ref: https://github.com/regen-network/regen-server/pull/404#discussion_r1370245861

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-server/407?planning-poker) with Zenhub @aaronc @blushi

**Comment by aaronc** [comment]
@blushi do you have any preference to whether we do this with separate tables or GRANT SELECT? My preference is separate tables because I think trying to use a combination or row level and column level security will make this overly complex. It's not possible to have row level security apply to just specific columns, whereas if we have separate tables we get fine grained row + column level security.

**Comment by blushi** [comment]
@aaronc As I've mentioned at stand up today, the separate tables approach sounds cleaner to me from a back-end perspective. But on the front-end, the GRANT / security definer function approach would allow to keep using the same generated `Account` type throughout the codebase and use a single query instead of 2 (get public and get private fields). That being said, we only need to query the private account fields for the authenticated accounts and we could encapsulate that into the `AuthProvider` that I added in https://github.com/regen-network/regen-web/pull/2198/files#diff-d00a8a8707394d135b94bab8a8a37a75b9e73c6f7a6473bcbf91d54bffed367d so I'm fine with using the separate table approach.
